### PR TITLE
Format and update README.md with more information

### PR DESCRIPTION
**Pull request by jonniesweb**
Hey Professor Barbeau. I thought that the README.md file could be prettied up a bit. Here are some changes that I think could help others.

### CODE REVIEW

**Comment by michelbarbeau** [comment]
Thanks a lot! I will integrate your changes.

Michel Barbeau

Carleton University

**Comment by michelbarbeau** [comment]
Is there a “one command way” to integrate your changes?

Michel Barbeau

Carleton University

**Comment by jonniesweb** [comment]
Yes, it's pretty simple. You can go to the pull request here: https://github.com/michelbarbeau/wireless-network-programming/pull/1

Then clicking on the "Merge Pull Request" button will integrate my changes into your project.

**Comment by michelbarbeau** [comment]
Thanks again for your feedback!

Michel Barbeau

Carleton University

**Pull request merged**
